site_name: Python Vacation
site_author: Pavel Anni
copyright: Pavel Anni
use_directory_urls: false


extra:
    palette:
        primary: 'green'
        accent: 'deep orange'

pages:
  - Home:  index.md
  - Intro: Python_vacation_outline.md
  - Day 0 - Hello, World: Python_vacation_day0.md
  - Day 1 - Text Dialogues: Python_vacation_day1.md
  - Day 2 - Menus: Python_vacation_day2.md
  - Day 3 - Errors: Python_vacation_day3.md
  - Day 4 - Functions: Python_vacation_day4.md

theme_dir: mkdocs-material/material
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - extra
  - fenced_code
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
