site_name: Python Vacation
site_author: Pavel Anni
copyright: Pavel Anni
use_directory_urls: false
site_url: 'http://pythonvacation.com'

theme:
    logo:
        icon: 'face'
    name: 'material'
    palette:
        primary: 'green'
        accent: 'deep orange'
    font:
        text: 'Roboto Slab'
        code: 'Roboto Mono'

extra:
    disqus: 'pythonvacation-com'
    social:
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/pavelanni/'


pages:
  - Home:  index.md
  - Day 0 - Coffee for Friends: Python_vacation_day00.md
  - Day 1 - Text Dialogues: Python_vacation_day01.md
  - Day 2 - Menus: Python_vacation_day02.md
  - Day 3 - Errors: Python_vacation_day03.md
  - Day 4 - Functions: Python_vacation_day04.md
  - Day 5 - Files: Python_vacation_day05.md
  - Day 6 - Main Menu: Python_vacation_day06.md
  - Day 7 - Web Interface: Python_vacation_day07.md
  - Day 8 - Making It Pretty: Python_vacation_day08.md
  - Day 9 - Getting Online: Python_vacation_day09.md
  - Day 10 - Databases: Python_vacation_day10.md
  - Day 11 - Automate It: Python_vacation_day11.md
  
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - extra
  - fenced_code
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
